name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release PR / Tag / Changelog
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
